/*
 * KAKAO System Planowania Wysy�ek
 * by Pawe� Pikus, Tomasz Pud�o
 */
package kakao;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static kakao.Sqlite.conn;

/**
 *
 * @author Lusiotron2015
 */
public class LoginPage extends javax.swing.JFrame {
    private String _imie;
    private String _nazwisko;
    private String _stanowisko;
    private String _username;
    private int _newPass;
    
    public String getImie() { return _imie;}
    public void setImie (String imie){_imie = imie;}
    public String getNazwisko(){return _nazwisko;}
    public void setNazwisko(String nazwisko){_nazwisko=nazwisko;}
    public String getStanowisko(){return _stanowisko;}
    public void setStanowisko(String stanowisko){_stanowisko = stanowisko;}
    public int getNewPass() {return _newPass;}
    public void setNewPass (int newPass) {_newPass = newPass;}
    public String getUser() {return _username;}
    public void setUser(String username) { _username = username;}
    
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtField_username = new javax.swing.JTextField();
        passField_password = new javax.swing.JPasswordField();
        LogIn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KAKAO ");
        setBackground(java.awt.Color.orange);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setText("login");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("hasło");

        txtField_username.setToolTipText("");

        LogIn.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        LogIn.setText("Zaloguj się");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton3.setText("Anuluj");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cocoa_logo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("System do Obsługi Zamówień w firmie Hanyang Polska");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(txtField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LogIn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3))
                                    .addComponent(passField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(67, 67, 67)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogIn)
                    .addComponent(jButton3))
                .addGap(44, 44, 44))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
        
        if (txtField_username.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Uzupełnij wszystkie pola!");
        } else if (passField_password.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "Uzupełnij wszystkie pola!");
        } else {
            String user = txtField_username.getText();
            char[] pass = passField_password.getPassword();
            String pwd = String.copyValueOf(pass);
            

            if (validate_login(user, pwd)) {
                //JOptionPane.showMessageDialog(null, "Logowanie udane!");
                System.out.print(getStanowisko()+" "+getNewPass()) ;
                setVisible(false);
                //ładuje główny widok
                if ("admin".equals(user)&&getNewPass()==0) {
                    AdminPage admin = new AdminPage(getImie(), getNazwisko(), getStanowisko());
                    admin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    admin.setSize(800, 600);
                    admin.setVisible(true);
                    admin.pack();

                }
                else if (getNewPass()==1){

                    PassChangePage passChange = new PassChangePage(getUser());
                    passChange.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    passChange.setSize(800, 600);
                    passChange.setVisible(true);
                    passChange.pack();
                }
                else {

                    NewJFrame ramka_glowna = new NewJFrame(getImie(), getNazwisko(), getStanowisko());
                    ramka_glowna.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    ramka_glowna.setSize(800, 600);
                    ramka_glowna.pack();
                    ramka_glowna.setVisible(true);
                }

            

        }else {
                JOptionPane.showMessageDialog(null, "Niepoprawna nazwa użytkownika lub hasło!");
            }
    }

    }//GEN-LAST:event_LogInActionPerformed

    private boolean validate_login(String username, String password) {
        try {
            KakaoDb kakaoDb = new KakaoDb("org.sqlite.JDBC", "jdbc:sqlite:Cocoa_v2.db");
            kakaoDb.getConnection();
            PreparedStatement pst = conn.prepareStatement("SELECT * from Pracownicy where username=? and password=?");

            pst.setString(1, username);
            pst.setString(2, password);
            setUser(username);
            
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                setImie(rs.getString("imie"));
                setNazwisko(rs.getString("nazwisko"));  
                setStanowisko(rs.getString("stanowisko"));
                setNewPass(rs.getInt("newPass"));
                
                return true;
            } else {
                return false;
            }
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogIn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField passField_password;
    private javax.swing.JTextField txtField_username;
    // End of variables declaration//GEN-END:variables
}
